server:
  port: 8081
#启用缓存的时候,模板只在第一次使用的时候解析一次,解析结果会被后续的请求所使用
#禁用Thymeleaf缓存
spring:
  thymeleaf:
    cache: false
taco:
  orders:
    pageSize: 10
  discount:
    codes:
      abcdef: 10
      jd2qcw: 20
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/tacocloud
    username: root
    password: XXXXXXXXX
logging:
  level:
    tacos: warn